# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9b22ea37303454f020efefcbf0367999837e146a75df9be93e30cf6fb1ff8ef921bb5ba3f16ee3e4e173b8a2c5dd08d57b8c15d6a95dfcebc8cc8e726cb42d4

  aliyun_oss:
    endpoint: http://oss-cn-hongkong.aliyuncs.com
    access_key_id: LTAIgKrhOy0x2luP
    access_key_secret: dQiSje01CjpAWZTfzjLq1hMaOW3Csx

test:
  secret_key_base: bba35898fab76564c8773b83e65e4962a3a1b77db3561bc2aaa735a8836b82273f2eb774c62f9cfc25985b2fb5cc35f63c92a8a7274b7f6484de7cf49e22a7a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  aliyun_oss:
    endpoint: http://oss-cn-hongkong.aliyuncs.com
    access_key_id: LTAIgKrhOy0x2luP
    access_key_secret: dQiSje01CjpAWZTfzjLq1hMaOW3Csx
